"""empty message

Revision ID: 001f535027d4
Revises: 
Create Date: 2019-11-20 15:43:23.171656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001f535027d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dersKodu', sa.String(length=50), nullable=True),
    sa.Column('dersAdi', sa.String(length=255), nullable=True),
    sa.Column('kredi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ders')
    # ### end Alembic commands ###
