"""empty message

Revision ID: 2c11c204a4c5
Revises: 707166266954
Create Date: 2019-12-04 16:12:22.175677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c11c204a4c5'
down_revision = '707166266954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanici',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kullaniciadi', sa.String(length=255), nullable=True),
    sa.Column('sifre', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kullanici')
    # ### end Alembic commands ###
