"""empty message

Revision ID: 707166266954
Revises: 001f535027d4
Create Date: 2019-11-20 15:45:55.286965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707166266954'
down_revision = '001f535027d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ders', sa.Column('ogretimGorevlisi', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ders', 'ogretimGorevlisi')
    # ### end Alembic commands ###
